// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wplay.Data;

#nullable disable

namespace Wplay.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Wplay.Models.EmailRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AttachmentsMetadata")
                        .HasColumnType("json")
                        .HasColumnName("attachments_metadata");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("html_body");

                    b.Property<string>("RawHeaders")
                        .HasColumnType("json")
                        .HasColumnName("raw_headers");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("sender");

                    b.Property<string>("Subject")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("subject");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("text_body");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_email_requests");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("email_requests_uuid_index");

                    b.HasIndex("EndpointId", "CreatedAt")
                        .HasDatabaseName("email_requests_endpoint_created_index");

                    b.ToTable("email_requests", (string)null);
                });

            modelBuilder.Entity("Wplay.Models.Endpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AuthCredentials")
                        .HasColumnType("json")
                        .HasColumnName("auth_credentials");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultResponseBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("default_response_body");

                    b.Property<string>("DefaultResponseHeaders")
                        .HasColumnType("json")
                        .HasColumnName("default_response_headers");

                    b.Property<int?>("DefaultStatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(200)
                        .HasColumnName("default_status_code");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsProtected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_protected");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ResponseDelay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("response_delay")
                        .HasComment("Response delay in milliseconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Webhook")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_endpoints");

                    b.HasIndex("UserId")
                        .HasDatabaseName("endpoints_userid_index");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("endpoints_uuid_index");

                    b.ToTable("endpoints", (string)null);
                });

            modelBuilder.Entity("Wplay.Models.WebhookRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<string>("ContentType")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("endpoint_id");

                    b.Property<string>("Headers")
                        .HasColumnType("json")
                        .HasColumnName("headers");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("ip_address");

                    b.Property<string>("Method")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("POST")
                        .HasColumnName("method");

                    b.Property<string>("QueryParameters")
                        .HasColumnType("json")
                        .HasColumnName("query_parameters");

                    b.Property<int>("ResponseCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(200)
                        .HasColumnName("response_code");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("TEXT")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_webhook_requests");

                    b.HasIndex("Uuid")
                        .HasDatabaseName("webhook_requests_uuid_index");

                    b.HasIndex("EndpointId", "CreatedAt")
                        .HasDatabaseName("webhook_requests_endpoint_created_index");

                    b.ToTable("webhook_requests", (string)null);
                });

            modelBuilder.Entity("Wplay.Models.EmailRequest", b =>
                {
                    b.HasOne("Wplay.Models.Endpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_requests_endpoints_endpoint_id");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("Wplay.Models.WebhookRequest", b =>
                {
                    b.HasOne("Wplay.Models.Endpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_webhook_requests_endpoints_endpoint_id");

                    b.Navigation("Endpoint");
                });
#pragma warning restore 612, 618
        }
    }
}
